# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-13 06:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.TextField(blank=True, null=True)),
                ('degree_name', models.TextField(blank=True, null=True)),
                ('passing_year', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'media/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.TextField(blank=True, null=True)),
                ('board', models.TextField(blank=True, null=True)),
                ('student_class', models.TextField(blank=True, null=True)),
                ('passing_year', models.CharField(blank=True, max_length=4, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoBackend.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoBackend.Profile'),
        ),
        migrations.AddField(
            model_name='academic',
            name='graduation',
            field=models.ManyToManyField(related_name='graduation', to='demoBackend.College'),
        ),
        migrations.AddField(
            model_name='academic',
            name='post_graduation',
            field=models.ManyToManyField(related_name='post_graduation', to='demoBackend.College'),
        ),
        migrations.AddField(
            model_name='academic',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demoBackend.Profile'),
        ),
        migrations.AddField(
            model_name='academic',
            name='school',
            field=models.ManyToManyField(related_name='school', to='demoBackend.School'),
        ),
    ]
